### PR TITLE
Refactoring codebase for Bolt 3.0

### PR DESCRIPTION
**Pull request by bobdenotter**

### CODE REVIEW

**Comment by GawainLynch** [comment]
The JS is failing:
```
Uncaught SyntaxError: Unexpected token < 
view/js/src/cheatsheet.js:1
```

**Comment by bobdenotter** [comment]
Are you sure you've pulled the latest?  :-) 

The source uses a different file: 

```
<script src="view/js/cheatsheet.js"></script>
```

And the file [you mention](https://github.com/bolt/cheatsheet/blob/refactoring-codebase/view/js/src/cheatsheet.js) does not have a single `<` in it.

**Comment by GawainLynch** [comment]
Fresh clone, and that was a copy/pasta response that I added in to try and load the un-minimised version… original assertion still valid.

**Comment by bobdenotter** [comment]
I'm probably being dumb here, but it doesn't make a lot of sense that you'd get that notice.

**Comment by GawainLynch** [comment]
It's JavaScript… so all bets are off as to the "Dumb Factor" and who is responsible :grin:

**Comment by bobdenotter** [comment]
@GawainLynch I PSR4-ified it, but I have no idea where your Javascript issues are coming from, though.. Typical 'Works for me'™ thing. You can show me tomorrow. :-)

**Comment by GawainLynch** [comment]
Whatever you did… it works for me now!

**Pull request merged**
